name: nosoapradio
description: A soapy radio experience
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  just_audio: ^0.9.31
  forge2d: ^0.11.0
  sensors: ^2.0.3
  get_it: ^7.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/white_large.jpg
    - assets/images/oily_bubble.png
    - assets/images/soap.png
    - assets/sounds/showersinging.wav
    - assets/sounds/big_pop.wav
  fonts:
    - family: ClimateCrisis
      fonts:
        - asset: fonts/Climate_Crisis/ClimateCrisis-Regular-VariableFont_YEAR.ttf
    - family: ShantellSans
      fonts:
        - asset: fonts/Shantell_Sans/ShantellSans-VariableFont_BNCE,INFM,SPAC,wght.ttf
